### ISSUE TITLE
[Question] RiotJS 3

### ISSUE THREAD

**Issue by ghost** [icd2k3/riot-opt-types-mixin#1]
This is great. 

I love the prop definitions that React has, although using an interface in Typescript is a bit better. I have used Riot-TS, but the developer hasn't updated it RiotJS 3.

Do you know if your mixin will work for RiotJS 3?

Thank you.

**Comment by icd2k3** [comment]
Hey apologies for the late reply on this, but React has since separated out its PropTypes into a standalone module here https://www.npmjs.com/package/prop-types rendering this repo obsolete. I recommend installing `prop-types` and including it in your riot project
